// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBTjO3zIh6MxNxuiRJWts2FNjiyYz0nU',
    appId: '1:169054060714:web:3ac73a661955e0d9e910d3',
    messagingSenderId: '169054060714',
    projectId: 'cloud-notes-app-a5b21',
    authDomain: 'cloud-notes-app-a5b21.firebaseapp.com',
    storageBucket: 'cloud-notes-app-a5b21.appspot.com',
    measurementId: 'G-582TLDZMT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClgq3qnenRxiMM9Gje33RWTSX6WQ_mUPQ',
    appId: '1:169054060714:android:31529fbdbcae448be910d3',
    messagingSenderId: '169054060714',
    projectId: 'cloud-notes-app-a5b21',
    storageBucket: 'cloud-notes-app-a5b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfH1_tEzYfXd7CI7pu5MMj6TQi9lhUZIY',
    appId: '1:169054060714:ios:46cfbcd9ed9380b6e910d3',
    messagingSenderId: '169054060714',
    projectId: 'cloud-notes-app-a5b21',
    storageBucket: 'cloud-notes-app-a5b21.appspot.com',
    iosBundleId: 'com.example.cloudNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfH1_tEzYfXd7CI7pu5MMj6TQi9lhUZIY',
    appId: '1:169054060714:ios:46cfbcd9ed9380b6e910d3',
    messagingSenderId: '169054060714',
    projectId: 'cloud-notes-app-a5b21',
    storageBucket: 'cloud-notes-app-a5b21.appspot.com',
    iosBundleId: 'com.example.cloudNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIBTjO3zIh6MxNxuiRJWts2FNjiyYz0nU',
    appId: '1:169054060714:web:7832e251b1244115e910d3',
    messagingSenderId: '169054060714',
    projectId: 'cloud-notes-app-a5b21',
    authDomain: 'cloud-notes-app-a5b21.firebaseapp.com',
    storageBucket: 'cloud-notes-app-a5b21.appspot.com',
    measurementId: 'G-XDVRXH9EYJ',
  );
}
